language: node_js
node_js:
- '4.2'
before_install:
- gem install jekyll
before_script:
- npm install -g grunt-cli
after_deploy:
- grunt gh-pages
sudo: false
env:
  global:
    secure: hylkH4bQkZDzSK+i39lMzrii99GsKJCkBHw1fu5HzGd+PdxCLOoWJeSlYFVyGpW4dBnzyRtX0S2iNO+71tU4KYEeSdi/wI/0Hb5r5nPZpyAyqcvQcqKPg28Zo0aChS4yDonXm8GquyarGrbTSxUgYTyQ8vd/quQzl04pgIRXLww=
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: kWKXkgv9GjyoYkerxpcUk3pJew7V33iPdToZhxtfbUeLwDMduL9ULZYOh1WHb4YqkHWuMCEMpQxG5fAybuPXwHMwDYd0E/CDtTdHlbB9nYWhKDbRSjSy6Mcw9EdTNGngX+KpmeSOSMtODhYef1j6kMDNn/LPqSJBLjL/+vcxdpg=
  skip_cleanup: true
  on:
    tags: true
    repo: flowbased/fbp-protocol
