language: node_js
node_js:
- lts/*
dist: trusty
sudo: false
before_install:
- gem install jekyll
before_script:
- npm install -g grunt-cli
after_deploy:
- grunt gh-pages
env:
  global:
    secure: hylkH4bQkZDzSK+i39lMzrii99GsKJCkBHw1fu5HzGd+PdxCLOoWJeSlYFVyGpW4dBnzyRtX0S2iNO+71tU4KYEeSdi/wI/0Hb5r5nPZpyAyqcvQcqKPg28Zo0aChS4yDonXm8GquyarGrbTSxUgYTyQ8vd/quQzl04pgIRXLww=
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: dwOEH5TP/e5Xypdhr9lZNAUyl+RVaIrEfbvjB3eBzrI8dMQ+qTVWwyWz8GUHprJm95iyB73aj/orMYlnDJ+bZwfSzViHRxuWNErq0HeSISYdiA1glTjScXx5tKgnKLQmGyNTy9JRdRsPSWXtmpJScq3vll6GthlgTgxwRnNRP9c=
  on:
    tags: true
    repo: flowbased/fbp-protocol
  skip_cleanup: true
